language: python

python:
    - "2.6"
    - "2.7"
    - "3.3"

env:
    - DJANGO=1.5
    - DJANGO=1.5.1
    - DJANGO=1.5.2
    - DJANGO=1.5.3
    - DJANGO=1.5.4
    - DJANGO=1.5.5
    - DJANGO=1.5.6
    - DJANGO=1.5.7
    - DJANGO=1.5.8
    - DJANGO=1.6
    - DJANGO=1.6.1
    - DJANGO=1.6.2
    - DJANGO=1.6.3
    - DJANGO=1.6.4
    - DJANGO=1.6.6

install:
    - pip install Django==$DJANGO
    - pip install -e .

script:
    - python run_tests.py

notifications:
    email:
        recipients:
          - jon@faustman.org
        on_success: never
        on_failure: always
